### ISSUE TITLE
[planner] add plan walker for visit the internal node eaiser

### ISSUE THREAD

**Issue by BohuTANG** [datafusedev/fuse-query#77]
Now we change all plan nodes to a array, if we using the walker pattern, we can do it easy and clear:
```
plan_node.walk((node)->Result<bool>) {
         match xx
}
```

This can be used at optimizer/pipeline_builder/rewritter:

- [x] Change Pipeline builder to  walk function #80 
- [x] Change Optimizer  to  walk function #80 
- [x] Change the plan display(Indent and graphvisual) to walk function #82

**Comment by leiysky** [comment]
I think this is requisite for Join operator. 

After refactoring optimizer with this, I'd like to implement Join framework.

**Comment by BohuTANG** [comment]
> I think this is requisite for Join operator.
> 
> After refactoring optimizer with this, I'd like to implement Join framework.

Thanks for your contribution!
Currently there are two predecessors:
one is the distributed execution engine(working in the processor, maybe done soon), and the other is plan's visitor.
When these arch foundations done, the rest(groupby/sort/join) can get up, cool.
